### ISSUE TITLE
[BUG] Bedrock players(Floodgate) can't pass "CAPTCHA_ON_POSITION_FAILED" mode

### ISSUE THREAD

**Issue by DJelly4K** [Elytrium/LimboFilter#10]
**Describe the bug**
In "CAPTCHA_ON_POSITION_FAILED" mode, players in Bedrock Edition (via Floodgate) cannot authenticate to join the game normally, they will be stuck in the verification world, and will be kicked out with a "You have exceeded the maximum Bot-Filter check time." prompt after a while
Java players can join normally

**To Reproduce**
1. Add limboapi and limbofilter and set mode to "CAPTCHA_ON_POSITION_FAILED"
2. test join, bedrock failed, java succeeded

**Expected behavior**
bedrock players can join normally

**Screenshots**
![image](https://user-images.githubusercontent.com/68630033/167280238-d40e6921-b98b-401d-a24d-0a8b7e13d742.png)
(The content of the screenshot is that the bedrock player is stuck in the verified world (virtual world), and there is a prompt that the verification is in progress, but there is no response)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.0.4-SNAPSHOT: https://github.com/Elytrium/LimboAPI/actions/runs/2250134443
 - LimboAuth 1.0.4-SNAPSHOT: https://github.com/Elytrium/LimboAPI/actions/runs/2250156315

 - /velocity dump link: https://dump.velocitypowered.com/oriqolapak.json

**Additional context**
i use machine translate

**Comment by DJelly4K** [comment]
> use "ONLY_CAPTCHA"

thanks, but i really want to use "CAPTCHA_ON_POSITION_FAILED", i dont want players always type captcha

**Comment by srlss123** [comment]
> 使用“ONLY_CAPTCHA”

Use this will kick bedrock when you give server CAPTCHA

**Comment by hevav** [comment]
Fixed
