### ISSUE TITLE
[ENHANCEMENT] КАПЧА НА ГОЛОВАХ

### ISSUE THREAD

**Issue by MichaelKozlovOfficial** [Elytrium/LimboFilter#102]
**Describe the feature you'd like to have implemented**
 
![Screenshot_1](https://github.com/user-attachments/assets/823963e4-c90b-4750-8545-ffe7d7f91261)

**Is your feature request related to an existing problem? Please describe.**
в данный момент практически любой антибот обошли

**Comment by SkyWatcher2019** [comment]
А это обойти будет ещё проще.
![no_misha](https://github.com/user-attachments/assets/e55d23d2-867b-48a0-b0ce-fdf4a94808c6)

**Comment by MichaelKozlovOfficial** [comment]
какой же кринж, я ничего плохого не написал, с нихуя закрыли с оскорблением меня

**Comment by sub-kek** [comment]
> какой же кринж, я ничего плохого не написал, с нихуя закрыли с оскорблением меня

Реально боже лол такой кринж, меня в дс за эмодзи рыбы замутили.
