### ISSUE TITLE
[ENHANCEMENT] Add "skip-checking-client" option

### ISSUE THREAD

**Issue by DJelly4K** [Elytrium/LimboFilter#12]
**Describe the feature you'd like to have implemented**
Add an new option called "skip-checking-client", if the client name is filled in, player can join directly without bot checks

**Is your feature request related to an existing problem? Please describe.**
#11 #10 I think is a good way for bedrock players, they can join directly

**Additional context**
/

**Comment by KurumiFake** [comment]
botters might change the brand to Geyser and bypass everything

**Comment by hevav** [comment]
It's easy to spoof brand packet and bypass everything.
We've fixed the bug with Geyser

**Comment by editon96** [comment]
Hey I get all Time Timed Out from LimboAPI how I can fix that?
