### ISSUE TITLE
[Suggestion] Включение капчи на время атаки

### ISSUE THREAD

**Issue by exzolink** [Elytrium/LimboFilter#2]
Приветствую.
Думаю всю суть я передал в заголовке, такая фича была бы очень полезна, чтобы не держать капчу постоянно и тем самым не отпугивать игроков.
Спасибо.

**Comment by hevav** [comment]
Не думаю что это хорошо. Ведь боты смогут заходить грубо говоря "раз в час", а потом как ордой спамить начнут. 
Все фичи, которые мешают заходить ботам, но не отпугивают игроков, уже есть в конфиге, например там есть параметр, чтобы защита лицензионных аккаунтов включалась не сразу, а при атаке.

**Comment by exzolink** [comment]
Не соглашусь. Обойти проверку падением сейчас не слишком большая проблема, поэтому даже если они начнут спамить, это не будет длится вечно, да, обычным игрокам придется ввести капчу, но это лучше, чем держать ее постоянно, даже вне атак. По поводу лиц. аккаунтов: мне кажется это последнее, что должно волновать, игроков с лицензией очень мало.

**Comment by hevav** [comment]
Если они начнуть спамить, и никто их самостоятельно не кикнет, то спам как раз будет вечный.
Но хорошо. Для того, чтобы отключить защиту при низком количестве подключений, есть параметр ALL_BYPASS в конфиге.

**Comment by exzolink** [comment]
Неверная капча или истечение времени разве не будет их кикать?

**Comment by exzolink** [comment]
И хотел еще спросить по поводу "unit of time" в чем они измеряются или как интерпретировать, например, NEED_TO_RECONNECT = 129?

**Comment by hevav** [comment]
Если боты зайдут пока капча отключена, как я сказал, будут заходить грубо "раз в час", то разумеется их никто, кроме человека, не кикнет.

**Comment by hevav** [comment]
> И хотел еще спросить по поводу "unit of time" в чем они измеряются или как интерпретировать, например, NEED_TO_RECONNECT = 129?

Количество человек, зашедших за время, указанное в конфиге

**Comment by exzolink** [comment]
В любом случае это куда практичнее, чем отключение защиты, в этом случае даже самые простые боты успеют зайти.

**Comment by exzolink** [comment]
Спасибо
