### ISSUE TITLE
Поддержка Spigot

### ISSUE THREAD

**Issue by F3F5** [Elytrium/LimboFilter#21]
Было бы классно :)

**Comment by SkyWatcher2019** [comment]
миша разлогинься

**Comment by F3F5** [comment]
> > Было бы классно :)у
> 
> так если даже на BungeeCord не сделали поддержку, то будут ли по твоему делать на Spigot?

Всегда можно сделатть, постараться надо.

**Comment by F3F5** [comment]
> > Было бы классно :)у
> 
> так если даже на BungeeCord не сделали поддержку, то будут ли по твоему делать на Spigot?

Это лишь мои пожелания

**Comment by F3F5** [comment]
> Зачем? Смысл фильтра это не допустить перегрузки сервера ботами, а тут бот как раз таки зайдут на сервер. Да, они не смогут использовать команды, чат, ходить, но им это и не нужно, так как свою задачу по перегрузке сервера они выполнили.

Такой ответ мой: допустим используем мы nantibot, почему с ним при 10 к ботов на гиге озу не лагает? Потому что они адаптировали поддерджку. Так же лимбо поможет против спам-ботов, не у всех есть прокси.

**Comment by Galster-dev** [comment]
LimboFilter называется LimboFilter потому что он находится на Limbo сервере с помощью LimboAPI. Есть фильтр будет поддерживать не лимбо сервера, то это уже совершенно другой проект
