### ISSUE TITLE
РАЗБЛОКИРОВАТЬ МИШУ ЛЕГЕНДУ ПОЖАЛУЙСТА Я ЕГО ФАНАТКА

### ISSUE THREAD

**Issue by F3F5** [Elytrium/LimboFilter#33]
РАЗБЛОКИРОВАТЬ МИШУ ЛЕГЕНДУ ПОЖАЛУЙСТА Я ЕГО ФАНАТКА

**Comment by 1050TItop** [comment]
Отказано, я его хейтер
И вообще, Миша лох объелся блох
