### ISSUE TITLE
[BUG] Капча говна

### ISSUE THREAD

**Issue by mdxd44** [Elytrium/LimboFilter#35]
**Describe the bug**
Если вкратце то разраб содиума сын паровоза

**To Reproduce**
 - Зайти на сервер с содиумом и пойти нахуй так как половину капчи не видно

**Expected behavior**
Как минимум пройти эту ебаную проверку говна

**Screenshots**
С содиумом:
![img](https://user-images.githubusercontent.com/67416904/206090529-a3d32ab9-daf0-4d7d-a945-2a4ecf8d1c6d.png)
Без содиума:
![without sodium](https://user-images.githubusercontent.com/67416904/206091352-ff86341b-09e5-4f49-ad92-5729d1185179.png)
Фулл список модов: (я скомпилил самую последнюю версию содиума с гита, но с той что на curseforge та же хуйня))
![modz](https://user-images.githubusercontent.com/67416904/206090605-0dea6a06-b6d2-45ac-9c7b-9c77da46bbc8.png)

**Server Info (please complete the following information):**
- Судя по инфе от автора сервера все плагины и велосити ласт

**Additional context**
Я конечно понимаю что вы, дети шлюх, нихуя не пофиксите, но зарепортить стоит

**Comment by hevav** [comment]
Вроде такое фиксится просто отдалением от капчи
Слишком близко не рендерится

**Comment by JNNGL** [comment]
кстати такое не только с модами но и на 1.12.2 и ниже

**Comment by Kamillaova** [comment]
> Вроде такое фиксится просто отдалением от капчи Т.е. слишком близко не рендерится
> 
> Ещё можно попробовать x и z сместить в положительную сторону

зарепортить в содиум????
