### ISSUE TITLE
[BUG] Kicked due to keepalive timeout

### ISSUE THREAD

**Issue by exosmium** [Elytrium/LimboFilter#36]
**Описание**
Время от времени игроков кикает LimboFilter с причиной "kicked due to keepalive timeout"

**Чтобы вызвать**
1. Установить плагины лимбо и подождать пару часов.

**Должно быть**
Мгновенное подключение игроков к серверу.

**Информация**
- Версии плагинов Limbo:
- LimboAPI 1.0.6
- LimboFilter 1.0.6

- Дамп Velocity: https://dump.velocitypowered.com/naveyohugu.json

- ![фок](https://user-images.githubusercontent.com/59437511/206202915-4a22f691-2ffa-48c9-8d1d-f5f6b55c0086.PNG)

**Comment by hevav** [comment]
Вариант 1: Смени хостинг или поднастрой сетевуху
Вариант 2: Поменяй ``max-ping`` в конфиге LimboFilter

**Comment by exosmium** [comment]
> Вариант 1: Смени хостинг или поднастрой сетевуху Вариант 2: Поменяй `max-ping` в конфиге LimboFilter

Можно конкретнее про "поднастрой сетевуху"?

**Comment by hevav** [comment]
Этому вопросу не место в данном issue
