### ISSUE TITLE
[BUG] Error to start proxy

### ISSUE THREAD

**Issue by 1Pootis1** [Elytrium/LimboFilter#41]
![image](https://user-images.githubusercontent.com/73141732/209481307-75add5a5-7bb6-4e03-a587-d48a38eb609d.png)

Version core: Paper 1.19.3
Version Velocity: velocity-3.1.2-SNAPSHOT-201
Version LimboFilter: limbofilter-1.0.8-SNAPSHOT
Version LimboAPI: limboapi-plugin-1.0.8-SNAPSHOT-73d28b35

**Comment by hevav** [comment]
apt install fontconfig

**Comment by Ne0N-droid** [comment]
> apt install fontconfig

thanks!
