### ISSUE TITLE
[BUG] Console error spam

### ISSUE THREAD

**Issue by DormantCat** [Elytrium/LimboFilter#42]
**Describe the bug**
Плагин выдаёт в консоль ошибки, при этом работает.

**To Reproduce**
Обновил плагин с 107 на 108 (с обновлением всего Limbo узла, а также ядра Velocity)

**Expected behavior**
Работа плагина без ошибок

**Screenshots**
![image](https://user-images.githubusercontent.com/40241759/212071440-07df7d79-dc50-4f74-af1c-83bf69986236.png)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
limboapi-plugin-1.0.10-SNAPSHOT-4ba2f026
limboauth-1.0.9
limbofilter-1.0.8

 - https://pastebin.com/PTimAW4r

**Comment by hevav** [comment]
Скинь фул лог или самую первую ошибку

**Comment by DormantCat** [comment]
> @DormantCat Скинь фул лог или самую первую ошибку

https://pastebin.com/VDhgJUTz

**Comment by hevav** [comment]
@DormantCat java.lang.OutOfMemoryError: Cannot reserve 524288 bytes of direct buffer memory (allocated: 10737412842, limit: 10737418240)
