### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to limbofilter [BUG] 

### ISSUE THREAD

**Issue by UnDef1nedd** [Elytrium/LimboFilter#44]
**Describe the bug**
A console error, when velocity with limbofilter is launched.

**To Reproduce**
1. Install Limbofilter
2. Start velocity
3. Voila!

**Expected behavior**
To launch normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/57291641/215271632-966d2f1a-6229-429b-91d5-54e0cbdc1124.png)

**Server Info:**
 - All Limbo plugins versions:
 - limboapi-1.1.4
 - LimboAuth.Social.Addon-1.0.10
 - limboauth-1.1.9
 - limbofilter-1.1.6

 - https://dump.velocitypowered.com/pujosuxusi.json

**Additional context**
None // В конфиге у меня кастом фонт отключён, я не знаю, на что он жалуется.

Error log: https://hastebin.com/qiretuhudo.sql

**Comment by Kamillaova** [comment]
sudo apt -y install fontconfig ttf-dejavu

**Comment by Kamillaova** [comment]
@UnDef1nedd 

sudo apt -y install fontconfig ttf-dejavu

**Comment by UnDef1nedd** [comment]
E: Unable to locate package ttf-dejavu

**Comment by UnDef1nedd** [comment]
The correct command:

`sudo apt -y install fontconfig fonts-dejavu`

**It worked. Issue resolved, thank you.**
