### ISSUE TITLE
[BUG] The captcha is not displayed on 1.12.2 | Не отображается капча на 1.12.2

### ISSUE THREAD

**Issue by iRedTea** [Elytrium/LimboFilter#75]
**Describe the bug**
The captcha is not displayed on 1.12.2, but on 1.16.5 all is going ok | Не отображается капча на 1.12.2, хотя на 1.16.5 все нормально

**To Reproduce**
1. Install and configure limbofilter
2. Join with 1.12.2 minecraft client

Tested on (velocity-3.2.0-SNAPSHOT-294, filter version [Dev-build 349ef51](https://github.com/Elytrium/LimboFilter/releases/tag/dev-build)) and 1.1.12

![chrome_GIfVVe9sXt](https://github.com/Elytrium/LimboFilter/assets/104762784/b297b863-184e-4368-b30c-6d25f9d795d9)

**Comment by JNNGL** [comment]
Обнови лимбоапи

**Comment by iRedTea** [comment]
Используется последняя версия limboapi-1.1.17-SNAPSHOT.jar. Куда обновлять?
