### ISSUE TITLE
[BUG] [REOPEN] The captcha is not displayed on 1.12.2 | Не отображается капча на 1.12.2

### ISSUE THREAD

**Issue by iRedTea** [Elytrium/LimboFilter#76]
**Describe the bug**
The captcha is not displayed on 1.12.2, but on 1.16.5 all is going ok | Не отображается капча на 1.12.2, хотя на 1.16.5 все нормально

**To Reproduce**
1. Install and configure limbofilter
2. Join with 1.12.2 minecraft client

Tested on (velocity-3.2.0-SNAPSHOT-294, filter version [Dev-build 349ef51](https://github.com/Elytrium/LimboFilter/releases/tag/dev-build)) and 1.1.12

![chrome_GIfVVe9sXt](https://github.com/Elytrium/LimboFilter/assets/104762784/b297b863-184e-4368-b30c-6d25f9d795d9)

USING LAST VERSION OF LIMBOAPI - limboapi-1.1.17-SNAPSHOT.jar !!!

**Comment by JNNGL** [comment]
<img width="1463" alt="image" src="https://github.com/Elytrium/LimboFilter/assets/45935949/cba4bc0d-eabc-4ecb-ac83-c33450188bee">
