### ISSUE TITLE
[ENHANCEMENT] Hex color support

### ISSUE THREAD

**Issue by livxbox5** [Elytrium/LimboFilter#78]
Can you add support for hex colors in limboFilter?

**Comment by JNNGL** [comment]
Use MiniMessage serializer. 
```
<color:#123456>Text</color>
```

**Comment by livxbox5** [comment]
FORMAT <#EE8700>TEXT-TEST</#FFD900>

**Comment by JNNGL** [comment]
> FORMAT <#EE8700>TEXT-TEST</#FFD900>

```
<gradient:#EE8700:#FFD900>text</gradient>
```

**Comment by livxbox5** [comment]
@[JNNGL](https://github.com/JNNGL) JNNGL

**Comment by livxbox5** [comment]
@[JNNGL](https://github.com/JNNGL) you are not the creator of the plugin why do you decide to close my request or not the creator actually https://github.com/Elytrium

**Comment by livxbox5** [comment]
@JNNGL and which one to put Available serializers: for <gradient:#EE8700:#FFD900>text</gradient>?
