### ISSUE TITLE
[BUG] Capcha generate error

### ISSUE THREAD

**Issue by deHasher** [Elytrium/LimboFilter#85]
Once when starting the server, the captcha didn't generate and it gave this error. Restarting the server helped.

https://gist.github.com/deHasher/a37fd07e9b587c083677cadc93232422

LimboAPI: 1.1.18
LimboFilter: 1.1.14
Velocity: 3.3.0-SNAPSHOT-310

**Comment by SkyWatcher2019** [comment]
Update LimboAPI and share your config

**Comment by deHasher** [comment]
> Update LimboAPI and share your config, also maybe out of ram

10 gb ram
LimboAPI cfg: https://gist.github.com/deHasher/262206f670d27ceb60ea351d47a20348
LimboFilter cfg: https://gist.github.com/deHasher/7462f1723478958ee5e9ee1c196dd1cf

**Comment by UserNugget** [comment]
Should be fixed in the latest LimboAPI devbuild. Reopen if still happens.
