### ISSUE TITLE
[BUG] После проверки вылазит сообщение о том что её не прошли.

### ISSUE THREAD

**Issue by ChappyBP** [Elytrium/LimboFilter#88]
![image](https://github.com/Elytrium/LimboFilter/assets/51001997/6f19290c-bef7-4285-99de-42f854d9b1d6)
все в названии

**Comment by ChappyBP** [comment]
каптчу заменил на капчу.

**Comment by ChappyBP** [comment]
ye

**Comment by ChappyBP** [comment]
ну

**Comment by UserNugget** [comment]
Solved in DMs
