### ISSUE TITLE
[BUG] Only 3 chunks will load on Paper 1.20.4 servers after joining with LimboFilter captcha

### ISSUE THREAD

**Issue by Alulom** [Elytrium/LimboFilter#89]
[BUG] Only view-distance of 3 chunks will load on Paper 1.20.4 servers behind Velocity when joining with LimboFilter captcha

To Reproduce:
1. Start a latest version of Velocity with only LimboAPI and LimboFilter installed (default configurations, latest versions).
2. Start a server behind Velocity, Paper or any of its forks, version 1.20.4 (important)!, with a view-distance of 4 or more.
3. Join the server, enter a captcha, and connect to the 1.20.4 server. Regardless of your view-distance setting, only a view distance of 3 chunks will load.
4. If you rejoin, the bug will disappear, and chunks will load normally.
5. If you reload LimboFilter and rejoin by reentering the captcha, the bug will reappear, and only a view distance of 3 chunks will load again.
This bug only affects servers running version 1.20.4 behind th proxy. As far as I checked, chunks on a 1.20.1 server will load normally regardless of how you join.

Expected behavior:
Chunks should load normally on every join.

Загружается только 3 чанка на серверах 1.20.4 под Velocity после входа с капчей лимбофильтра.
Шаги для Воспроизведения:
1. Запустите последнюю версию Velocity с установленными LimboAPI и LimboFilter (стандартные конфигурации, последние версии).
2. Запустите сервер под Velocity, используя Paper или форк, версию 1.20.4 (важно), с view-distance 4 или больше.
3. Присоединитесь к серверу, введите капчу и подключитесь к серверу 1.20.4. Независимо от настройки дальности видимости, загрузится только дальность видимости 3 чанка.
4. Если вы перезайдете, баг исчезнет, и чанки будут загружаться нормально.
5. Если вы перезагрузите LimboFilter и снова присоединитесь, введя капчу, баг снова появится, и  дальность видимости будет 3  чанка.
Баг влияет только на серверы под велосити на 1.20.4. Чанки на серверах 1.20.1 и ниже будут загружаються нормально, независимо от того, как входить (с капчей или без).

Screenshots:
1. Server config.
![0view_distance_config](https://github.com/Elytrium/LimboFilter/assets/97155476/68926727-8e4f-4588-98f0-34987963edb2)

2. Joining with captcha
![1joining_with_captcha](https://github.com/Elytrium/LimboFilter/assets/97155476/c578a656-30f5-49b1-9bc9-03f9f560cf27)

3.  Only 3 view distance loads on 1.20.4 server
![3only3chunksload](https://github.com/Elytrium/LimboFilter/assets/97155476/64dbfd5d-5454-40d6-93af-f87a9f7ce765)

4. If you rejoin with no captcha chunks will load normal
![4rejoin_normal_load](https://github.com/Elytrium/LimboFilter/assets/97155476/9f85300c-d810-4d85-b051-35b997c24c8e)

5. If you reload LimboFilter and rejoin entering a captcha 3 chunks will load again.

Server Info:

 - LimboFilter Release 1.1.15, downloaded from https://github.com/Elytrium/LimboFilter/releases/download/1.1.15/limbofilter-1.1.15.jar
 - LimboAPI Release 1.1.20, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.1.20/limboapi-1.1.20.jar

 - latest Velocity, downloaded from https://api.papermc.io/v2/projects/velocity/versions/3.3.0-SNAPSHOT/builds/343/downloads/velocity-3.3.0-SNAPSHOT-343.jar

- latest Paper

- velocity dump https://pastebin.com/HQwrvbem

**Comment by UserNugget** [comment]
[LimboAPI issue](https://github.com/Elytrium/LimboAPI/commit/0e3061f7e702397c2ee3298a738702ad0213360f) as it skip ClientSettings packet, will be fixed in 1.1.21
