### ISSUE TITLE
[BUG] exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl

### ISSUE THREAD

**Issue by 864063334** [Elytrium/LimboFilter#9]
**Describe the bug**
When I enter the server using the domain name, it stays for only 7 seconds and then kicks me off the server

**To Reproduce**
1. Access to the server using the domain name
2. The lower part shows seven seconds without moving
3. Kick out of the server

**Expected behavior**

**Screenshots**
![QQ截图20220506150638](https://user-images.githubusercontent.com/61329086/167095756-9e661afa-9db6-4edd-9f79-e2eb51e1a7e6.png)
![QQ截图20220506150700](https://user-images.githubusercontent.com/61329086/167095764-3091eaea-bc0b-4ab8-9723-06a6e937ea79.png)
![QQ截图20220506150711](https://user-images.githubusercontent.com/61329086/167095788-2c1a98fd-cc3d-4ac6-9b1a-482e782b735f.png)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [e.g. LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
 - [e.g. LimboAuth 1.0.4, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
 - LimboFilter 1.0.4from https://github.com/Elytrium/LimboFilter/actions

 - /velocity dump link [https://dump.velocitypowered.com/umayiyidam.json]
**Additional context**
[latest.log](https://github.com/Elytrium/LimboFilter/files/8638646/latest.log)

**Comment by hevav** [comment]
I don't think that this is LimboAPI issue
But try to reproduce with the latest LimboAPI/LimboAuth/LimboFilter/Velocity builds
