### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sonogioo** [Elytrium/LimboFilter#93]
**Describe the bug**
Nothing too complicated, i just cant join my server cause of this error: When trying to join most of the time i get this error: internal exception:io.netty.handler.codec.Corrupted Frame Exception: length wider than 21-bit

(when uninstalling limbofilter it works fine and i can join)

**To Reproduce**
1. Standard Configs, no changes at all.
2. Just try to join the server
3. I Have this plugins:

![Screenshot 2024-04-09 124043](https://github.com/Elytrium/LimboFilter/assets/166505147/745f112c-c488-453e-8ecc-27a5795e4d3e)
![Screenshot 2024-04-09 124038](https://github.com/Elytrium/LimboFilter/assets/166505147/c9b1ce4f-f42b-4d3d-b6e5-67a0e3382d86)
![Screenshot 2024-04-09 124028](https://github.com/Elytrium/LimboFilter/assets/166505147/bc880169-0754-455f-b161-24f4d8903628)

**Expected behavior**
When trying to join most of the time i get this error: internal exception:io.netty.handler.codec.Corrupted Frame Exception: length wider than 21-bit

**Screenshots**
![2024-04-09_12 39 13](https://github.com/Elytrium/LimboFilter/assets/166505147/16a56b02-e0ae-47fb-8955-0ced1e2871f1)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
- limboapi-1.1.22.jar
- limbofilter-1.1.16.jar
- Latest Version of Velocity

[velocity-dump-2024-04-09-10-38-36.json](https://github.com/Elytrium/LimboFilter/files/14917463/velocity-dump-2024-04-09-10-38-36.json)

**Comment by DHCPCD9** [comment]
Download dev build of velocity

**Comment by mdxd44** [comment]
please reopen and attach logs if this issue is still present on latest velocity and limbo* builds
