### ISSUE TITLE
[BUG] Can't create plugin limbofilter

### ISSUE THREAD

**Issue by Martyfree123** [Elytrium/LimboFilter#95]
**Describe the bug**
When the server status up the console provides errors for LimboAPI and LimboFilter. Both plugins fail to start.

**To Reproduce**
1. Install both plugins
2. Start server
3. See errors in Console

**Expected behavior**
Expected plugins to start up normally

**Screenshots**
Full snip of alerts from the console:
https://pastebin.com/w86BKgjU

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 LimboFilter 1.1.27
 LimboAPI 1.1.23
 
 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]
 https://pastebin.com/i1Nsi642

**Additional context**
Not sure what's causing this. This is my first time using LimboFilter.

**Comment by mdxd44** [comment]
you should use new velocity build
https://api.papermc.io/v2/projects/velocity/versions/3.3.0-SNAPSHOT/builds/386/downloads/velocity-3.3.0-SNAPSHOT-386.jar

**Comment by Martyfree123** [comment]
I will try it, thanks!

**Comment by Martyfree123** [comment]
Same issue occurs on 3.3.0

**Comment by mdxd44** [comment]
that is, you're still running an old velocity build

**Comment by Martyfree123** [comment]
Sorry I was looking at version and not build. Attempted to install build 386 but I get `this version of the Java Runtime only recognizes class file versions up to 52.0`. I have Java 17 installed so I'm not sure what the issue is?

**Comment by mdxd44** [comment]
this message says java 8 still in use , run `java --version` in terminal to ensure that you're really using java 17

**Comment by Martyfree123** [comment]
Got build 386 loaded with Java 17. Both plugins are now working. Thank you!
